// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttgtiwvfxsvvugixzial.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0Z3Rpd3ZmeHN2dnVnaXh6aWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NDQzNzUsImV4cCI6MjA1NzQyMDM3NX0.5VoQrPYJSTm8Ve00p_tY4Z0vPemfHrrLVPCCVRZYOMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);